In [17]:
#Data Pre-procesing Step  
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd
from sklearn import metrics
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

#importing datasets  
data_set= pd.read_csv(r"C:\Users\semil\Documents\Breast Cancer Data.csv")

In [18]:
#Extracting Independent and dependent Variable  
X= data_set.iloc[:, 2:31].values  
y= data_set.iloc[:, 1].values  
print(X.shape, y.shape)

(569, 29) (569,)


In [19]:
#BAGGING TREE MODEL

# evaluate bagging algorithm for classification

# define the model
model = BaggingClassifier()

# evaluate the model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')


for train_index, test_index in cv.split(X, y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    

model.fit(X,y)
y_pred = model.predict(X_test)

# report performance
print('Accuracy for Bagging Trees: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix for Bagging Trees: ')
print(cm)

Accuracy for Bagging Trees: 0.950 (0.028)
Confusion Matrix for Bagging Trees: 
[[35  0]
 [ 0 21]]


In [22]:
#LDA MODEL

#Split the data
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.2, random_state=0)


#Create model 
clf = LinearDiscriminantAnalysis()
clf.fit(X_train_2, y_train_2)

y_pred_2 = clf.predict(X_test_2)

#Evaluate model
print('Accuracy of the LDA model is: ' + str(accuracy_score(y_test_2, y_pred_2)))
cm = confusion_matrix(y_test_2, y_pred_2)
print('The confusion matrix of the LDA model is:')
print(cm)


Accuracy of the LDA model is: 0.9473684210526315
The confusion matrix of the LDA model is:
[[67  0]
 [ 6 41]]


In [21]:
#NAIVE BAYES MODEL


# Split dataset into training set and test set
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(X, y, test_size=0.3,random_state=109) # 70% training and 30% test


#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train_3, y_train_3)

#Predict the response for test dataset
y_pred_3 = gnb.predict(X_test_3)

# Model Accuracy
print("Accuracy for Naive Bayes model:",metrics.accuracy_score(y_test_3, y_pred_3))
cm = confusion_matrix(y_test_3, y_pred_3)
print("Confusion Matrix for Naive Bayes model:")
print(cm)

Accuracy for Naive Bayes model: 0.9532163742690059
Confusion Matrix for Naive Bayes model:
[[106   2]
 [  6  57]]
